apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-and-mongodb
  template:
    metadata:
      labels:
        app: app-and-mongodb
    spec:
      containers:
      - name: nodejs-app
        image: santhoshii/njs-app:latest
        ports:
        - containerPort: 3005
        env:
        - name: MONGODB_URI
          value: "mongodb://localhost:27017/returnExchangeDB"
        - name: PORT
          value: "3005"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "returnExchangeDB"
 