version: '3.8'
 
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mynetwork1
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: return-exchange
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongo:27017/returnExchangeDB
    networks:
      - mynetwork1
 
networks:
  mynetwork1:
    driver: bridge
 
